apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    name: standard-resize
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
